# Generated by Django 6.0.7 on 2026-07-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged')], default='Good', max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated'), ('Reserved', 'Reserved'), ('Under Maintenance', 'Under Maintenance'), ('Lost', 'Lost'), ('Retired', 'Retired'), ('Disposed', 'Disposed')], default='Available', max_length=30)),
                ('shared_bookable', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.assetcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
            ],
        ),
    ]
