# Generated by Django 6.0.7 on 2026-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
