# Generated by Django 6.0.7 on 2026-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='resolved_at',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='technician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
